# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/vito/11vo semestre/Procesamiento y Análisis de Imágenes/Tarea 2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/vito/11vo semestre/Procesamiento y Análisis de Imágenes/Tarea 2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/vito/11vo semestre/Procesamiento y Análisis de Imágenes/Tarea 2/CMakeFiles" "/home/vito/11vo semestre/Procesamiento y Análisis de Imágenes/Tarea 2/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/vito/11vo semestre/Procesamiento y Análisis de Imágenes/Tarea 2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named funciones

# Build rule for target.
funciones: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 funciones
.PHONY : funciones

# fast build rule for target.
funciones/fast:
	$(MAKE) -f CMakeFiles/funciones.dir/build.make CMakeFiles/funciones.dir/build
.PHONY : funciones/fast

#=============================================================================
# Target rules for targets named graph

# Build rule for target.
graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph
.PHONY : graph

# fast build rule for target.
graph/fast:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/build
.PHONY : graph/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named mst

# Build rule for target.
mst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mst
.PHONY : mst

# fast build rule for target.
mst/fast:
	$(MAKE) -f CMakeFiles/mst.dir/build.make CMakeFiles/mst.dir/build
.PHONY : mst/fast

funciones.o: funciones.cpp.o
.PHONY : funciones.o

# target to build an object file
funciones.cpp.o:
	$(MAKE) -f CMakeFiles/funciones.dir/build.make CMakeFiles/funciones.dir/funciones.cpp.o
.PHONY : funciones.cpp.o

funciones.i: funciones.cpp.i
.PHONY : funciones.i

# target to preprocess a source file
funciones.cpp.i:
	$(MAKE) -f CMakeFiles/funciones.dir/build.make CMakeFiles/funciones.dir/funciones.cpp.i
.PHONY : funciones.cpp.i

funciones.s: funciones.cpp.s
.PHONY : funciones.s

# target to generate assembly for a file
funciones.cpp.s:
	$(MAKE) -f CMakeFiles/funciones.dir/build.make CMakeFiles/funciones.dir/funciones.cpp.s
.PHONY : funciones.cpp.s

graph.o: graph.cpp.o
.PHONY : graph.o

# target to build an object file
graph.cpp.o:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/graph.cpp.o
.PHONY : graph.cpp.o

graph.i: graph.cpp.i
.PHONY : graph.i

# target to preprocess a source file
graph.cpp.i:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/graph.cpp.i
.PHONY : graph.cpp.i

graph.s: graph.cpp.s
.PHONY : graph.s

# target to generate assembly for a file
graph.cpp.s:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/graph.cpp.s
.PHONY : graph.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

mst.o: mst.cpp.o
.PHONY : mst.o

# target to build an object file
mst.cpp.o:
	$(MAKE) -f CMakeFiles/mst.dir/build.make CMakeFiles/mst.dir/mst.cpp.o
.PHONY : mst.cpp.o

mst.i: mst.cpp.i
.PHONY : mst.i

# target to preprocess a source file
mst.cpp.i:
	$(MAKE) -f CMakeFiles/mst.dir/build.make CMakeFiles/mst.dir/mst.cpp.i
.PHONY : mst.cpp.i

mst.s: mst.cpp.s
.PHONY : mst.s

# target to generate assembly for a file
mst.cpp.s:
	$(MAKE) -f CMakeFiles/mst.dir/build.make CMakeFiles/mst.dir/mst.cpp.s
.PHONY : mst.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... funciones"
	@echo "... graph"
	@echo "... main"
	@echo "... mst"
	@echo "... rebuild_cache"
	@echo "... funciones.o"
	@echo "... funciones.i"
	@echo "... funciones.s"
	@echo "... graph.o"
	@echo "... graph.i"
	@echo "... graph.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mst.o"
	@echo "... mst.i"
	@echo "... mst.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

